name: Ubuntu

on:
  pull_request:
  push:
    branches-ignore:
      - release/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        java_version: [ 11, 17 ]

    steps:
      - uses: actions/checkout@v3
      - name: "Set up JDK ${{ matrix.java_version }}"
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
          cache: sbt

      - name: build
        run: sbt test

      - name: check finds test todos
        run: |
          ./scripts/dev/assemble.sh
          if ./scripts/todo-checker.sh ; then 
            echo "todo-checker should have found todos and fail but exit code was 0" && false
          else
            echo "todo-checker found errors as expected"
          fi
      - name: Check no own todos
        if: matrix.java_version == 11
        uses: tegonal/workflow-helper@v0.3.0
        with:
          commands: 'todo-checker -i "wh#\d+"'
